# Generated by Django 3.1.1 on 2021-07-27 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted instance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active instance')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Category Name')),
                ('details', models.CharField(blank=True, max_length=256, verbose_name='Category Details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted instance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active instance')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Sub Category Name')),
                ('details', models.CharField(blank=True, max_length=256, verbose_name='Sub Category Details')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='categories.category', verbose_name='Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted instance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active instance')),
                ('name', models.CharField(db_index=True, max_length=256, verbose_name='Product Name')),
                ('details', models.CharField(blank=True, max_length=256, verbose_name='Product Details')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='categories.subcategory', verbose_name='Sub Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
