# Generated by Django 3.1.1 on 2021-07-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Category Name'),
        ),
    ]
